//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskViewer.Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int MainTaskId { get; set; }
        public string Name { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public int Status { get; set; }
    
        public virtual User User { get; set; }

        public Task(int userId, int mainTaskId, string name, DateTime creationDate, Nullable<DateTime> expirationDate = null)
        {
            UserId = userId;
            MainTaskId = mainTaskId;
            Name = name;
            CreationDate = creationDate;
            ExpirationDate = expirationDate;
            Status = (int)StatusEnum.Unassigned;
        }

        public Task()
        {

        }
    }
}
