//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskViewer.Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int Id { get; set; }
        public int UsersId { get; set; }
        public string Name { get; set; }
        public int MainTaskId { get; set; }

        public Task()
        {

        }
        public Task(int usersId,string name,int mainTaskId)
        {
            UsersId = usersId;
            Name = name;
            MainTaskId = mainTaskId;
        }
        public virtual User User { get; set; }
    }
}
